# highD: Inference Bezier 20m + K8, 80ep @ 10Hz
input_data:
  dataset: ['highd_ngsim']
  subject: vehicle
  frame_subsample: 1
  train_folder: train
  val_folder: val
  test_folder: test
  observed_steps: 15
  prtediction_step: 25
  points_per_position: 2
  reduction_ratio: 16
  relation_neighbor_limit_meter: 20.0
  relation_neighbor_limit_k: 8
  augment: false

training:
  train: false
  save_model: false
  output_projection: false
  device: 'cuda:0'
  batch_size: 16
  experiment_root: 'experiments/vehicle'
  model_dir: 'experiments/vehicle/train/train_highd_20m_oneshot_bezier_80ep_k8'
  run_name: 'inference_highd_20m_oneshot_bezier_80ep_k8'
  backbone: 'transformer'
  output_type: 'one_shot_bezier'
  num_heads: 2
  num_layers: 2
  ffl: 16
  dropout: 0.2
