# highD: Bezier+Residual v2 30m + K12, 80ep @ 10Hz (TCN) - mb-l40s
input_data:
  dataset: ['highd_ngsim']
  subject: vehicle
  frame_subsample: 1
  train_folder: train
  val_folder: val
  test_folder: test
  observed_steps: 15
  prtediction_step: 25
  points_per_position: 2
  reduction_ratio: 16
  relation_neighbor_limit_meter: 30.0
  relation_neighbor_limit_k: 12
  relation_neighbor_random_sample: true
  augment: false

training:
  save_model: true
  train: true
  validation_interval: 1
  output_projection: false
  use_residual_separation: true
  use_tcn: true
  tcn_kernel_size: 3
  tcn_num_layers: 2
  device: 'cuda:0'
  batch_size: 16
  weight_decay: 0.0005
  milestones: [40, 60, 70]
  epoches: 80
  experiment_root: 'experiments/vehicle'
  run_name: 'train_highd_30m_oneshot_bezier_80ep_residual_v2_tcn_k12'
  backbone: 'transformer'
  output_type: 'one_shot_bezier'
  model_dir: 'experiments/vehicle/train/train_highd_30m_oneshot_bezier_80ep_residual_v2_tcn_k12'
  learning_rate: 0.01
  num_heads: 2
  num_layers: 2
  ffl: 16
  dropout: 0.2
