# Local: Inference KAN-VT-Former, 15m filter (uses train_kan_15m_v1)
input_data:
  dataset: ['eth', 'hotel', 'univ', 'zara1', 'zara2']
  subject: 'pedestrian'
  use_kan: 'head_kan'
  train_folder: 'train'
  val_folder: 'test'
  test_folder: 'test'
  observed_steps: 8
  prtediction_step: 12
  points_per_position: 2
  reduction_ratio: 16
  relation_neighbor_limit_meter: 15.0

training:
  save_model: false
  train: false
  validation_interval: 1
  device: 'cuda:0'
  batch_size: 256
  weight_decay: 0.001
  milestones: [10, 30, 45]
  epoches: 20
  experiment_root: 'experiments/pedestrian'
  run_name: 'inference_kan_15m_v1'
  selected_model: 'kan_best'

  model_profiles:
    original:
      backbone: 'transformer'
      output_type: 'mlp'
      model_dir: 'experiments/pedestrian/train/train_original_10m_v2'
      learning_rate: 0.01
      num_heads: 2
      num_layers: 2
      ffl: 16
      dropout: 0.7
    kan_best:
      backbone: 'transformer'
      output_type: 'kan'
      model_dir: 'experiments/pedestrian/train/train_kan_15m_v1'
      learning_rate: 0.01
      num_heads: 2
      num_layers: 2
      ffl: 16
      dropout: 0.7
    mamba:
      backbone: 'mamba'
      output_type: 'mlp'
      model_dir: 'models/pb/2026-02-15_17-39-19'
      learning_rate: 0.01
      num_heads: 2
      num_layers: 2
      ffl: 16
      dropout: 0.7
      mamba_d_state: 16
      mamba_d_conv: 4
      mamba_expand: 2
