# NGSIM: Inference 30m+aug 20ep
input_data:
  dataset: ['ngsim']
  subject: vehicle
  train_folder: train_1k
  val_folder: val_1k
  test_folder: test_1k
  observed_steps: 15
  prtediction_step: 25
  points_per_position: 2
  reduction_ratio: 16
  relation_neighbor_limit_meter: 30.0
  augment: false

training:
  save_model: false
  train: false
  device: 'cuda:0'
  batch_size: 16
  epoches: 20
  experiment_root: 'experiments/vehicle'
  run_name: 'inference_ngsim_30m_aug_20ep'
  backbone: 'transformer'
  output_type: 'mlp'
  model_dir: 'experiments/vehicle/train/train_ngsim_30m_aug_20ep'
  learning_rate: 0.01
  num_heads: 2
  num_layers: 2
  ffl: 16
  dropout: 0.2
