input_data:
  # dataset : ['Carolinas_eyelevel']
  # dataset : ['Carolinas_highAngle']
  dataset : ['ngsim']
  subject: 'vehicle'
  # train_folder: 'train'
  # val_folder: 'val'
  # test_folder: 'test'
  # dataset : ['ngsim']
  train_folder: 'train_1k1'
  val_folder: 'val_1k1'
  test_folder: 'test_1k1'
  observed_steps : 15
  prtediction_step : 25
  points_per_position : 2
  reduction_ratio : 16 # swap between 16 for observed_steps 10 and 15 and 10 for observed_steps 5

training:
  save_model : False
  train : False
  validation_interval : 1
  save_folder : 'vb'
  learning_rate : 0.01
  milestones : [10,30,45]
  epoches : 20
  device : 'cuda:0'
  # device : 'cuda:1'
  # device : 'cuda:3'
  weight_decay : 0.0005
  model_dir : "/project/vtrajectory/models/VT_Former-main/models/vb/2023-10-19_23-20-11"
  # model_dir : None
  batch_size : 16
  num_heads: 4
  num_layers: 8
  ffl: 256
  dropout : 0.2